# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.4.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.4.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/a558989/Projects/word2vec

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/a558989/Projects/word2vec

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.4.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.4.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.4.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.4.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.4.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.4.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	cd /Users/a558989/Projects/word2vec && $(CMAKE_COMMAND) -E cmake_progress_start /Users/a558989/Projects/word2vec/CMakeFiles /Users/a558989/Projects/word2vec/dmlc-core/CMakeFiles/progress.marks
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f CMakeFiles/Makefile2 dmlc-core/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/a558989/Projects/word2vec/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f CMakeFiles/Makefile2 dmlc-core/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f CMakeFiles/Makefile2 dmlc-core/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f CMakeFiles/Makefile2 dmlc-core/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/a558989/Projects/word2vec && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
dmlc-core/CMakeFiles/dmlccore.dir/rule:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f CMakeFiles/Makefile2 dmlc-core/CMakeFiles/dmlccore.dir/rule
.PHONY : dmlc-core/CMakeFiles/dmlccore.dir/rule

# Convenience name for target.
dmlccore: dmlc-core/CMakeFiles/dmlccore.dir/rule

.PHONY : dmlccore

# fast build rule for target.
dmlccore/fast:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/build
.PHONY : dmlccore/fast

# Convenience name for target.
dmlc-core/CMakeFiles/dmlccore_lint.dir/rule:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f CMakeFiles/Makefile2 dmlc-core/CMakeFiles/dmlccore_lint.dir/rule
.PHONY : dmlc-core/CMakeFiles/dmlccore_lint.dir/rule

# Convenience name for target.
dmlccore_lint: dmlc-core/CMakeFiles/dmlccore_lint.dir/rule

.PHONY : dmlccore_lint

# fast build rule for target.
dmlccore_lint/fast:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore_lint.dir/build.make dmlc-core/CMakeFiles/dmlccore_lint.dir/build
.PHONY : dmlccore_lint/fast

src/config.o: src/config.cc.o

.PHONY : src/config.o

# target to build an object file
src/config.cc.o:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/config.cc.o
.PHONY : src/config.cc.o

src/config.i: src/config.cc.i

.PHONY : src/config.i

# target to preprocess a source file
src/config.cc.i:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/config.cc.i
.PHONY : src/config.cc.i

src/config.s: src/config.cc.s

.PHONY : src/config.s

# target to generate assembly for a file
src/config.cc.s:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/config.cc.s
.PHONY : src/config.cc.s

src/data.o: src/data.cc.o

.PHONY : src/data.o

# target to build an object file
src/data.cc.o:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/data.cc.o
.PHONY : src/data.cc.o

src/data.i: src/data.cc.i

.PHONY : src/data.i

# target to preprocess a source file
src/data.cc.i:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/data.cc.i
.PHONY : src/data.cc.i

src/data.s: src/data.cc.s

.PHONY : src/data.s

# target to generate assembly for a file
src/data.cc.s:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/data.cc.s
.PHONY : src/data.cc.s

src/io.o: src/io.cc.o

.PHONY : src/io.o

# target to build an object file
src/io.cc.o:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/io.cc.o
.PHONY : src/io.cc.o

src/io.i: src/io.cc.i

.PHONY : src/io.i

# target to preprocess a source file
src/io.cc.i:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/io.cc.i
.PHONY : src/io.cc.i

src/io.s: src/io.cc.s

.PHONY : src/io.s

# target to generate assembly for a file
src/io.cc.s:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/io.cc.s
.PHONY : src/io.cc.s

src/io/input_split_base.o: src/io/input_split_base.cc.o

.PHONY : src/io/input_split_base.o

# target to build an object file
src/io/input_split_base.cc.o:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/io/input_split_base.cc.o
.PHONY : src/io/input_split_base.cc.o

src/io/input_split_base.i: src/io/input_split_base.cc.i

.PHONY : src/io/input_split_base.i

# target to preprocess a source file
src/io/input_split_base.cc.i:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/io/input_split_base.cc.i
.PHONY : src/io/input_split_base.cc.i

src/io/input_split_base.s: src/io/input_split_base.cc.s

.PHONY : src/io/input_split_base.s

# target to generate assembly for a file
src/io/input_split_base.cc.s:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/io/input_split_base.cc.s
.PHONY : src/io/input_split_base.cc.s

src/io/line_split.o: src/io/line_split.cc.o

.PHONY : src/io/line_split.o

# target to build an object file
src/io/line_split.cc.o:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/io/line_split.cc.o
.PHONY : src/io/line_split.cc.o

src/io/line_split.i: src/io/line_split.cc.i

.PHONY : src/io/line_split.i

# target to preprocess a source file
src/io/line_split.cc.i:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/io/line_split.cc.i
.PHONY : src/io/line_split.cc.i

src/io/line_split.s: src/io/line_split.cc.s

.PHONY : src/io/line_split.s

# target to generate assembly for a file
src/io/line_split.cc.s:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/io/line_split.cc.s
.PHONY : src/io/line_split.cc.s

src/io/local_filesys.o: src/io/local_filesys.cc.o

.PHONY : src/io/local_filesys.o

# target to build an object file
src/io/local_filesys.cc.o:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/io/local_filesys.cc.o
.PHONY : src/io/local_filesys.cc.o

src/io/local_filesys.i: src/io/local_filesys.cc.i

.PHONY : src/io/local_filesys.i

# target to preprocess a source file
src/io/local_filesys.cc.i:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/io/local_filesys.cc.i
.PHONY : src/io/local_filesys.cc.i

src/io/local_filesys.s: src/io/local_filesys.cc.s

.PHONY : src/io/local_filesys.s

# target to generate assembly for a file
src/io/local_filesys.cc.s:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/io/local_filesys.cc.s
.PHONY : src/io/local_filesys.cc.s

src/io/recordio_split.o: src/io/recordio_split.cc.o

.PHONY : src/io/recordio_split.o

# target to build an object file
src/io/recordio_split.cc.o:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/io/recordio_split.cc.o
.PHONY : src/io/recordio_split.cc.o

src/io/recordio_split.i: src/io/recordio_split.cc.i

.PHONY : src/io/recordio_split.i

# target to preprocess a source file
src/io/recordio_split.cc.i:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/io/recordio_split.cc.i
.PHONY : src/io/recordio_split.cc.i

src/io/recordio_split.s: src/io/recordio_split.cc.s

.PHONY : src/io/recordio_split.s

# target to generate assembly for a file
src/io/recordio_split.cc.s:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/io/recordio_split.cc.s
.PHONY : src/io/recordio_split.cc.s

src/recordio.o: src/recordio.cc.o

.PHONY : src/recordio.o

# target to build an object file
src/recordio.cc.o:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/recordio.cc.o
.PHONY : src/recordio.cc.o

src/recordio.i: src/recordio.cc.i

.PHONY : src/recordio.i

# target to preprocess a source file
src/recordio.cc.i:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/recordio.cc.i
.PHONY : src/recordio.cc.i

src/recordio.s: src/recordio.cc.s

.PHONY : src/recordio.s

# target to generate assembly for a file
src/recordio.cc.s:
	cd /Users/a558989/Projects/word2vec && $(MAKE) -f dmlc-core/CMakeFiles/dmlccore.dir/build.make dmlc-core/CMakeFiles/dmlccore.dir/src/recordio.cc.s
.PHONY : src/recordio.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/strip"
	@echo "... dmlccore_lint"
	@echo "... install/local"
	@echo "... dmlccore"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/data.o"
	@echo "... src/data.i"
	@echo "... src/data.s"
	@echo "... src/io.o"
	@echo "... src/io.i"
	@echo "... src/io.s"
	@echo "... src/io/input_split_base.o"
	@echo "... src/io/input_split_base.i"
	@echo "... src/io/input_split_base.s"
	@echo "... src/io/line_split.o"
	@echo "... src/io/line_split.i"
	@echo "... src/io/line_split.s"
	@echo "... src/io/local_filesys.o"
	@echo "... src/io/local_filesys.i"
	@echo "... src/io/local_filesys.s"
	@echo "... src/io/recordio_split.o"
	@echo "... src/io/recordio_split.i"
	@echo "... src/io/recordio_split.s"
	@echo "... src/recordio.o"
	@echo "... src/recordio.i"
	@echo "... src/recordio.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/a558989/Projects/word2vec && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

